### ISSUE TITLE
Error when trying to install the package in -e

### ISSUE THREAD

**Issue by esloch** [osl-incubator/containers-sugar#30]
* containers-sugar version:
> Version: 1.2.0
> docker-compose version 1.29.2, build unknown
* Python version:
> Python 3.9.16
* Operating System:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
5.19.0-29-generic
```

### Description
Error when creating the environment and installing the package in editable mode

### What I Did

``` 
$ pip install -e containers-sugar
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.3.2 requires jsonschema<5.0.0,>=4.10.0, but you have jsonschema 3.2.0 which is incompatible.
``` 
```

**Comment by xmnlab** [comment]
not really sure about your workflow, but we remove some dependencies.
so, it would  help to have less dependencies' conflict
