### ISSUE TITLE
Send signal to Kill build/start process when ctrl+C is pressed

### ISSUE THREAD

**Issue by luabida** [osl-incubator/containers-sugar#62]
It won't stop the containers build if kill signal is sent to the process

**Comment by xmnlab** [comment]
this code should be doing this: https://github.com/osl-incubator/containers-sugar/blob/main/containers_sugar/sugar.py#L122

we need to investigate why it is not doing that

**Comment by xmnlab** [comment]
maybe we could try with `RunningCommand.kill_group()`

**Comment by xmnlab** [comment]
IIRC this was fixed. feel free to reopen this issue if the problem persists
